language: node_js

repo_token: hyvwZkspK1ws6HKgUD4IWbzowpfRYITgC

node_js: 

  - 0.10.35
  - 4.4.5
  - 6.2.0

services: 
  - redis

script: npm test

after_script: npm run cov

after_success: 
  "curl -L -l https://coveralls.io/repos/github/navyxie/redlock-node/badge.svg?branch=master"